# %%
"""
        Z LINE CROSSTALK MEASUREMENT

Measure flux crosstalk between two Z lines by sweeping:

    detector_z (self compensation)
    crosstalk_z (disturbing line)

The resonance shift line gives the crosstalk slope.

Result:
    detector_z = k * crosstalk_z + b
    crosstalk = -1 / k

Prerequisites:
    - x180 operation calibrated for the qubits (detector).
    - readout IQ blobs calibrated for the qubits (detector) if you use state discrimination, otherwise the IQ amplitude will be shown.
By-products:
    - x180_xtalk operation in qubit's xy control. It's generated by scaling the amplitude of the original x180 by a length-calculated factor.
Bugs report:
    - Reach out to Ratis.
"""

# %% Imports
from qualibrate import QualibrationNode, NodeParameters
from quam_libs.components import QuAM, Transmon, TransmonPair
from quam.components.pulses import DragCosinePulse
from quam_libs.macros import qua_declaration, active_reset, readout_state, active_reset_simple
from quam_libs.lib.qua_datasets import convert_IQ_to_V
from quam_libs.lib.plot_utils import QubitGrid, grid_iter
from quam_libs.lib.save_utils import fetch_results_as_xarray, load_dataset
from quam_libs.lib.fit import peaks_dips

from qualang_tools.results import progress_counter, fetching_tool
from qualang_tools.loops import from_array
from qualang_tools.multi_user import qm_session
from qualang_tools.units import unit

from qm.qua import *
from qm import SimulationConfig

import numpy as np
import matplotlib.pyplot as plt
from typing import Literal, Optional, List


# %% Node parameters
class Parameters(NodeParameters):

    qubits: Optional[List[str]] = ["q3", "q4"]
    source: str = "coupler_q3_q4"

    num_averages: int = 300

    operation_len_in_ns: float = 1_000

    min_source_flux: float = -0.2
    max_source_flux: float = 0.2
    num_flux_points: int = 51

    qubits_flux_span: float = 0.1
    qubits_freq_shift: float = 0  #MHz, currently no use

    flux_point_joint_or_independent: Literal["joint", "independent"] = "independent"
    reset_type: Literal["active", "thermal"] = "active"

    simulate: bool = False
    simulation_duration_ns: int = 2000
    use_state_discrimination:bool = True
    timeout: int = 100
    load_data_id: Optional[int] = None


node = QualibrationNode(
    name="03x_flux_xtalk_Rabi",
    parameters=Parameters()
)

assert node.parameters.operation_len_in_ns % 4 == 0, "operation_len_in_ns must be a multiple of 4 ns !"

# %% Initialize QuAM
# Class containing tools to help handling units and conversions.
u = unit(coerce_to_integer=True)
# Instantiate the QuAM class from the state file
machine = QuAM.load()



# Open Communication with the QOP
if node.parameters.load_data_id is None:
    qmm = machine.connect()

# Get the relevant QuAM components
if node.parameters.qubits is None or node.parameters.qubits == "":
    qubits = machine.active_qubits
else:
    qubits = [machine.qubits[q] for q in node.parameters.qubits]

# Remove any qubit whose id matches the source
for qubit in qubits[:]:  # iterate over a copy to safely remove
    if qubit.id == node.parameters.source:
        print(f"Removing qubit '{qubit.id}' because it matches the source '{node.parameters.source}'")
        qubits.remove(qubit)
try:
    source = machine.qubits[node.parameters.source]
except:
    try:
        source = machine.qubit_pairs[node.parameters.source]
    except:
        raise ValueError("node.parameters.source is not a qubit or a coupler")

num_qubits = len(qubits)
# %% QUA program
n_avg = node.parameters.num_averages  # The number of averages

# Adjust the pulse duration and amplitude to drive the qubit into a mixed state - can be None
operation_len = node.parameters.operation_len_in_ns

for q in qubits:
    pi_dura = q.xy.operations['x180'].length
    factor = operation_len/pi_dura
    
    q.xy.operations['x180_xtalk'] = DragCosinePulse(
        digital_marker="ON",
        axis_angle=0.0,
        amplitude= (1/factor) * q.xy.operations['x180'].amplitude,
        length=operation_len,
        alpha=q.xy.operations['x180'].alpha,
        anharmonicity=q.anharmonicity
    )

operation = "x180_xtalk"
# Generate the OPX and Octave configurations
config = machine.generate_config()
z_step = node.parameters.num_flux_points

qubits_f_shift = int(node.parameters.qubits_freq_shift * u.MHz)
source_dzs = np.linspace(node.parameters.min_source_flux, node.parameters.max_source_flux, z_step)

qubits_dzs = np.linspace(-node.parameters.qubits_flux_span / 2, node.parameters.qubits_flux_span / 2, z_step)
flux_point = node.parameters.flux_point_joint_or_independent

with program() as flux_xtalk:

    I, I_st, Q, Q_st, n, n_st = qua_declaration(num_qubits=num_qubits)
    state = [declare(int) for _ in range(num_qubits)]
    state_st = [declare_stream() for _ in range(num_qubits)]
    s_dz = declare(fixed)
    q_dz = declare(fixed)

    machine.apply_all_couplers_to_min()

    for i, qubit in enumerate(qubits):
        if not node.parameters.simulate:
            machine.set_all_fluxes(flux_point=flux_point, target=qubit)
            qubit.z.settle()
            # if isinstance(source, TransmonPair):
            #     source.coupler.settle()
            # else:
            #     source.z.settle()
            align()


        with for_(n, 0, n < n_avg, n + 1):
            save(n, n_st)
            with for_(*from_array(s_dz, source_dzs)):
                with for_(*from_array(q_dz, qubits_dzs)):
                    if not node.parameters.simulate:
                        if node.parameters.reset_type == "active":
                            active_reset(qubit, "readout")
                        else:
                            qubit.resonator.wait(qubit.thermalization_time * u.ns)
                            qubit.align()
                    # Update the qubit frequency
                    # qubit.xy.update_frequency(qubit.xy.intermediate_frequency + qubits_f_shift, keep_phase=True)
                    duration = operation_len // 4
                    
                    align()
                    if isinstance(source, TransmonPair):
                        source.coupler.play("const", amplitude_scale=s_dz / source.coupler.operations["const"].amplitude, duration=duration)
                    else:
                        source.z.play("const", amplitude_scale=s_dz / source.z.operations["const"].amplitude, duration=duration)
                    qubit.z.play("const", amplitude_scale=q_dz / qubit.z.operations["const"].amplitude, duration=duration)
                    qubit.xy.play(operation)
                    align()
                    # qubit.xy.update_frequency(qubit.xy.intermediate_frequency, keep_phase=True)
                    align()

                    # Measure the state of the resonators
                    if not node.parameters.use_state_discrimination:
                        qubit.resonator.measure("readout", qua_vars=(I[i], Q[i]))
                        # save data
                        save(I[i], I_st[i])
                        save(Q[i], Q_st[i])
                    else:
                        readout_state(qubit, state[i])
                        save(state[i], state_st[i])
                    # Update the qubit frequency


    with stream_processing():

        n_st.save("n")
        for i, detector in enumerate(qubits):
            if not node.parameters.use_state_discrimination:
                I_st[i].buffer(len(qubits_dzs)).buffer(len(source_dzs)).average().save(f"I{i + 1}")
                Q_st[i].buffer(len(qubits_dzs)).buffer(len(source_dzs)).average().save(f"Q{i + 1}")
            else:
                state_st[i].buffer(len(qubits_dzs)).buffer(len(source_dzs)).average().save(f"state{i + 1}")


# %% {Simulate_or_execute}
if node.parameters.simulate:
    # Simulates the QUA program for the specified duration
    simulation_config = SimulationConfig(duration=node.parameters.simulation_duration_ns * 4)  # In clock cycles = 4ns
    job = qmm.simulate(config, flux_xtalk, simulation_config)
    # Get the simulated samples and plot them for all controllers
    samples = job.get_simulated_samples()
    waveform_report = job.get_simulated_waveform_report()
    waveform_report.create_plot(samples, plot=True)
    fig, ax = plt.subplots(nrows=len(samples.keys()), sharex=True)
    for i, con in enumerate(samples.keys()):
        plt.subplot(len(samples.keys()), 1, i + 1)
        samples[con].plot()
        plt.title(con)
    plt.tight_layout()
    # Save the figure
    node.results = {"figure": plt.gcf()}
    node.machine = machine
    node.save()

elif node.parameters.load_data_id is None:
    with qm_session(qmm, config, timeout=node.parameters.timeout) as qm:
        job = qm.execute(flux_xtalk)
        results = fetching_tool(job, ["n"], mode="live")
        while results.is_processing():
            # Fetch results
            n = results.fetch_all()[0]
            # Progress bar
            progress_counter(n, n_avg, start_time=results.start_time)

# %% {Data_fetching_and_dataset_creation}
if not node.parameters.simulate:
    if node.parameters.load_data_id is not None:
        ds, machine, json_data, detector, source, node.parameters = load_dataset(node.parameters.load_data_id, parameters = node.parameters)
    else:
        # Fetch the data from the OPX and convert it into a xarray with corresponding axes (from most inner to outer loop)
        ds = fetch_results_as_xarray(job.result_handles, qubits, {"qubits_z": qubits_dzs, "source_z": source_dzs})
        # Convert IQ data into volts
        if not node.parameters.use_state_discrimination:
            ds = convert_IQ_to_V(ds, qubits)
            # Derive the amplitude IQ_abs = sqrt(I**2 + Q**2)
            ds = ds.assign({"IQ_abs": np.sqrt(ds["I"] ** 2 + ds["Q"] ** 2)})
        # Add the resonator RF frequency axis of each qubit to the dataset coordinates for plotting
        ds = ds.assign_coords(qubits_z=ds.qubits_z, source_z=ds.source_z)  # convert to V
        ds.qubits_z.attrs = {"long_name": "qubits z bias", "units": "V"}
        ds.source_z.attrs = {"long_name": "source z bias", "units": "V"}

    # Add the dataset to the node
    node.results = {"ds": ds}


    from scipy.optimize import curve_fit
    import xarray as xr
    def get_fit_error(pos_data, source_z, y_axis_range):
        """
        Calculates the fitting error based on the RMSE (Root Mean Squared Error) and converts it to a percentage of the y-axis range.
        """
       
        # linear fit
        fit = pos_data.polyfit("source_z", 1)
        coeff = fit.polyfit_coefficients
        predicted = coeff.sel(degree=1) * source_z + coeff.sel(degree=0)
        
        # 1. RMSE calculation
        rmse = np.sqrt(((pos_data - predicted) ** 2).mean().values)
        
        # 2. RMSE error to % of y-axis range
        error_percent = (rmse / y_axis_range)
        
        return error_percent, fit

    def fit_gaussian_peaks_compatible(da, dim) -> xr.Dataset:
        """
        Performs Gaussian fitting on 1D data along the specified dimension and returns the fitted parameters as an xarray Dataset
        """
        def _gaussian_fit_1d(y):
            x = da.coords[dim].values
            # initial guess for fitting parameters
            offset_g = np.min(y)
            amp_g = np.max(y) - offset_g
            mu_g = x[np.argmax(y)]
            sigma_g = (x.max() - x.min()) / 10
            
            try:
                popt, _ = curve_fit(
                    lambda x, a, m, s, o: a * np.exp(-(x - m)**2 / (2 * s**2)) + o,
                    x, y, p0=[amp_g, mu_g, sigma_g, offset_g]
                )
                # popt: [amp, mu, sigma, offset]
                # to FWHM: width = 2 * sqrt(2 * ln2) * sigma ≈ 2.355 * sigma
                return np.array([popt[1], popt[2] * 2.355, popt[0], popt[3]])
            except:
                return np.array([np.nan] * 4)

        raw_results = xr.apply_ufunc(
            _gaussian_fit_1d, da,
            input_core_dims=[[dim]],
            output_core_dims=[["params"]],
            vectorize=True
        ).assign_coords(params=["position", "width", "amplitude", "base_line"])

        
        return xr.Dataset({
        "position": raw_results.sel(params="position").drop_vars("params"),
        "width": raw_results.sel(params="width").drop_vars("params"),
        "amplitude": raw_results.sel(params="amplitude").drop_vars("params"),
        "base_line": raw_results.sel(params="base_line").drop_vars("params")
        })

    # %% {Data_analysis}
    # Find the resonance dips for each flux point
    data_source = ds.state if node.parameters.use_state_discrimination else ds.I
    # peaks_dips method
    try:
        peaks_old = peaks_dips(data_source, dim="qubits_z", prominence_factor=6)
        error_old, fit_old = get_fit_error(peaks_old.position, ds.source_z, y_axis_range=node.parameters.qubits_flux_span) # in % of the qubits flux span
    except Exception:
        error_old, fit_old = np.inf, None

    # Gaussian Fitting method
    try:
        peaks_new = fit_gaussian_peaks_compatible(data_source, dim="qubits_z")
        error_new, fit_new = get_fit_error(peaks_new.position, ds.source_z, y_axis_range=node.parameters.qubits_flux_span) # in % of the qubits flux span
    except Exception:
        error_new, fit_new = np.inf, None

    if error_new < error_old:
        print(f"Gaussian Fitting (MSE: {error_new:.2%})")
        peaks = peaks_new
        linear_fit_results = fit_new
        fitting_error = error_new
    else:
        print(f"peaks_dips (MSE: {error_old:.2%})")
        peaks = peaks_old
        linear_fit_results = fit_old
        fitting_error = error_old


    # Extract relevant fitted parameters
    coeff = linear_fit_results.polyfit_coefficients
    fitted = coeff.sel(degree=1) * ds.source_z + coeff.sel(degree=0)
    qubits_bias = coeff[1]
    xtalk = -coeff[0]

    # Save fitting results
    fit_results = {}
    for q in qubits:
        fit_results[q.name] = {}
        if not np.isnan(xtalk.sel(qubit=q.name).values):
            if flux_point == "independent":
                offset = q.z.independent_offset
            elif flux_point == "joint":
                offset = q.z.joint_offset
            else:
                offset = 0.0
            print(f"flux crosstalk from {source.name} to {q.name} is {xtalk.sel(qubit=q.name).values:.2f}")

            fit_results[q.name]["qubit_bias"] = float(qubits_bias.sel(qubit=q.name).values)
            fit_results[q.name]["crosstalk"] = float(xtalk.sel(qubit=q.name).values)
        else:
            print(f"No fit for qubit {q.name}")
            fit_results[q.name]["qubit_bias"] = np.nan
            fit_results[q.name]["crosstalk"] = np.nan
    node.results["fit_results"] = fit_results

    # %% {Plotting}
    grid = QubitGrid(ds, [q.grid_location for q in qubits])
    for ax, qubit in grid_iter(grid):
        if not node.parameters.use_state_discrimination:
            ds.loc[qubit].I.plot(
                ax=ax, add_colorbar=True, x="source_z", y="qubits_z", robust=True
            )
        else:
            ds.loc[qubit].state.plot(
                ax=ax, add_colorbar=True, x="source_z", y="qubits_z", robust=True
            )
        peaks.position.loc[qubit].plot(ax=ax, ls="", marker=".", color="gray", ms=10, alpha=0.5)
        fitted.loc[qubit].plot(ax=ax, ls=":", color="r")
        
        ax.set_ylabel("qubit z bias (V)")
        ax.set_title(f"{qubit['qubit']}: {xtalk.sel(qubit=qubit['qubit']).values:.2%}")
        ax.set_xlabel("source z bias (V)")

    grid.fig.suptitle(f"Flux crosstalk from {source.name}\n Flux duration = {operation_len} ns\n Fitting RMSE: {fitting_error:.2%} (of y range)")
    plt.tight_layout()
    plt.show()
    node.results["figure_raw"] = grid.fig

        
    # %% {Update_state}
    if node.parameters.load_data_id is None:
        if isinstance(source, TransmonPair):
            source_wiring = source.coupler.opx_output
        else:
            source_wiring = source.z.opx_output

        with node.record_state_updates():

            # Append Flux Xtalk. matrix. into source's extras, for furthere uasage in the future.
            if "flux_xtalk_matrix" not in source.extras:
                source.extras["flux_xtalk_matrix"] = {}
                for q in qubits:
                    if not np.isnan(xtalk.sel(qubit=q.name).values):
                        source.extras["flux_xtalk_matrix"][q.name] = xtalk.sel(qubit=q.name).item()
            else:
                for q in qubits:
                    if not np.isnan(xtalk.sel(qubit=q.name).values):
                        source.extras["flux_xtalk_matrix"][q.name] = xtalk.sel(qubit=q.name).item()

            # Flux Xtalk compensation: add the compensation value into the target qubit's z opx output port.
            for q in qubits:
                if not np.isnan(xtalk.sel(qubit=q.name).values):
                    if source_wiring.controller_id == q.z.opx_output.controller_id and source_wiring.fem_id == q.z.opx_output.fem_id:
                        source_port = source_wiring.port_id
                        if q.z.opx_output.crosstalk is not None:
                            q.z.opx_output.crosstalk[source_port] += -1*xtalk.sel(qubit=q.name).values # -1 is because we add this value on target port. 
                        else:
                            q.z.opx_output.crosstalk = {source_port: -1*xtalk.sel(qubit=q.name).values}
                    else:
                        print(f"{q.name} didn't be updated because its flux output is on different controller or fem with the source. Source port: {source_wiring.controller_id} fem-{source_wiring.fem_id} port-{source_wiring.port_id}, target port: {q.z.opx_output.controller_id} fem-{q.z.opx_output.fem_id} port-{q.z.opx_output.port_id}")


    # %% {Save_results}
    node.results["ds"] = ds
    node.outcomes = {q.name: "successful" for q in qubits}
    node.results["initial_parameters"] = node.parameters.model_dump()
    node.machine = machine
    node.save()

# %%